name: INRcompress
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - absl-py=1.0.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py36h8f6f2f9_0
  - async-timeout=3.0.0=py36_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py36h8f6f2f9_1001
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - certifi=2021.5.30=py36h5fab9bb_0
  - cffi=1.14.6=py36h400218f_0
  - chardet=4.0.0=py36h5fab9bb_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - coverage=4.0.3=py36_1
  - cryptography=35.0.0=py36hb60f036_0
  - cudatoolkit=11.0.3=h15472ef_9
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.0=py36h7b6447c_0
  - dask-core=2.25.0=py_0
  - dataclasses=0.8=pyh787bdff_2
  - decorator=5.1.0=pyhd8ed1ab_0
  - enum34=1.1.10=py36h9f0ad1d_2
  - freetype=2.10.4=h0708190_1
  - google-auth=2.3.3=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpcio=1.35.0=py36hce63b2e_0
  - h5py=3.1.0=nompi_py36hc1bc4f5_100
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=67.1=he1b5a44_0
  - idna=3.1=pyhd3deb0d_0
  - idna_ssl=1.1.0=pyhd8ed1ab_1002
  - imagecodecs-lite=2019.12.3=py36h92226af_3
  - imageio=2.9.0=py_0
  - importlib-metadata=3.10.1=py36h5fab9bb_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - kiwisolver=1.3.1=py36h605e78d_1
  - krb5=1.19.2=hcc1bbae_3
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libcurl=7.80.0=h2574ce0_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libgomp=11.2.0=h1d223b6_11
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libnghttp2=1.43.0=h812cca2_1
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.15.8=h780b84a_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.0.9=he6b73bb_1
  - libuv=1.42.0=h7f98852_0
  - libzlib=1.2.11=h36c2ea0_1013
  - markdown=3.3.4=py36h06a4308_0
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py36h5fdd944_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36h8c4c3a4_2
  - mkl_fft=1.2.0=py36h68bb277_1
  - mkl_random=1.2.0=py36h7c3b610_1
  - multidict=5.2.0=py36h8f6f2f9_0
  - ncurses=6.2=h58526e2_4
  - networkx=2.3=py_0
  - ninja=1.10.2=h4bd325d_1
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1l=h7f98852_0
  - pathlib=1.0.1=py36h5fab9bb_4
  - pillow=5.4.1=py36h34e0f95_0
  - pip=21.3.1=pyhd8ed1ab_0
  - protobuf=3.15.8=py36hc4f0c31_0
  - pyaml=20.4.0=pyh9f0ad1d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.3.0=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyrsistent=0.14.11=py36h27cfd23_0
  - pysocks=1.7.1=py36h5fab9bb_3
  - python=3.6.13=hffdb5ce_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - pytorch=1.7.1=py3.6_cuda11.0.221_cudnn8.0.5_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.1.1=py36h7b6447c_2
  - pyyaml=5.4.1=py36h8f6f2f9_1
  - readline=8.1=h46c0cb4_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - scikit-image=0.17.2=py36h284efc9_4
  - scipy=1.5.3=py36h81d768a_1
  - setuptools=49.6.0=py36h5fab9bb_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h9cd32fc_2
  - tensorboard=2.7.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py36hc39840e_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tifffile=2019.7.26.2=py36_0
  - tk=8.6.11=h27826a3_1
  - toolz=0.11.2=pyhd8ed1ab_0
  - torchaudio=0.7.2=py36
  - torchvision=0.8.2=py36_cu110
  - tornado=6.1=py36h8f6f2f9_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing-extensions=4.0.0=hd8ed1ab_0
  - typing_extensions=4.0.0=pyha770c72_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py36h8f6f2f9_2
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - pip:
      - torchtext==0.3.1
      - pytorch-ignite==0.4.4
      - ipython==7.16.1
      - protobuf==3.7.1
      - future==0.17.1
      - bokeh==1.2.0
      - pandas==1.1.1
      - holoviews==1.12.7
      - hvplot==0.4.0
      - osqp==0.6.1
      - onnx==1.8.1
      - timm==0.3.1

